# GSB 5544 — Week 6 Iteration Keys — INSTRUCTOR SOLUTION
*Two activities from textbook [Chapter 7, Iteration](https://ds-ml-with-python.github.io/Course-Textbook/06-iteration.html), in one notebook*

| | Activity | Questions |
|---|---|---|
| **Part 1** | PA 6.2 — Iteration | 1 – 8: *99 Bottles* verses as a list, `sqrt_pos_unvec` / `sqrt_pos_vec`, `sing_verse_3` with `map()` and a lambda, penguin categories with `.apply` |
| **Part 2** | Practice Activity: Iteration | 0 – 3: the penguin categories on their own (the same task as Part 1, Questions 6 – 8, with the counting code supplied) |

Each part is self-contained — Part 2 reloads the data and redefines its function — so either can be run alone.
Every answer follows the same five beats: **Approach → code → What the code does → Expected output → Common mistakes**.

---
## Part 1 — PA 6.2: Iteration — INSTRUCTOR SOLUTION
*Textbook: [Chapter 7, Iteration](https://ds-ml-with-python.github.io/Course-Textbook/06-iteration.html)
— for loops, vectorized functions, `map()`, lambda functions, and `.apply()`*

**How to use this notebook.** Each question is answered in the same five beats: **Approach** (the idea, in a
sentence or two) → **code** (complete and executed) → **What the code does** (piece by piece) → **Expected
output** → **Common mistakes** (what students actually do, and the symptom you will see on their screen).

**The one idea to keep returning to:** *first ask whether the function is vectorized.* If it works on a whole
array (`np.sqrt`, boolean masks), use it directly. If it only works on one value — anything with an `if` inside —
you must iterate: a `for` loop, `map()` for lists, or `.apply(axis=1)` for the rows of a data frame. A lambda is
the glue that fixes the arguments that should *not* change.

The questions refer to "the code above" in the textbook: `sing_verse()` from *99 Bottles of Beer*. It is
reproduced here so the notebook runs on its own.

In [1]:
import numpy as np
import pandas as pd

# From the textbook (Section 7.2): one verse, returned as a string rather than printed
def sing_verse(num):
  song = str(num) + " bottles of beer on the wall \n" + str(num) + " bottles of beer \n" + " take one down, pass it around, \n" + str(num-1) + " bottles of beer on the wall \n"
  return song

print(sing_verse(99))

99 bottles of beer on the wall 
99 bottles of beer 
 take one down, pass it around, 
98 bottles of beer on the wall 



1.  Complete the Check-in before Section 7.2.1:

    Modify the code above so that instead of creating one long string, we create a list, where each element is one of the verses of the song.


### Solution 1 — a list of verses instead of one long string

**Approach.** The textbook's loop starts with an empty **string** and adds each verse with `+`. Start with an
empty **list** instead and add each verse as a one-element list (or `.append()` it).

In [2]:
verses = []                                  # empty LIST, not an empty string
for i in range(100, 97, -1):
  verses = verses + [sing_verse(i)]          # list + list -> a longer list

print(type(verses), len(verses))
verses

<class 'list'> 3


['100 bottles of beer on the wall \n100 bottles of beer \n take one down, pass it around, \n99 bottles of beer on the wall \n',
 '99 bottles of beer on the wall \n99 bottles of beer \n take one down, pass it around, \n98 bottles of beer on the wall \n',
 '98 bottles of beer on the wall \n98 bottles of beer \n take one down, pass it around, \n97 bottles of beer on the wall \n']

In [3]:
# The same loop with .append(), which adds one element in place
verses = []
for i in range(100, 97, -1):
  verses.append(sing_verse(i))

print(verses[0])                             # the first verse is still one readable string

100 bottles of beer on the wall 
100 bottles of beer 
 take one down, pass it around, 
99 bottles of beer on the wall 



In [4]:
print("".join(verses))                       # and the list can be glued back into the whole song

100 bottles of beer on the wall 
100 bottles of beer 
 take one down, pass it around, 
99 bottles of beer on the wall 
99 bottles of beer on the wall 
99 bottles of beer 
 take one down, pass it around, 
98 bottles of beer on the wall 
98 bottles of beer on the wall 
98 bottles of beer 
 take one down, pass it around, 
97 bottles of beer on the wall 



**What the code does.**
- `verses = []` — the "empty object" to accumulate into is now a list.
- `verses + [sing_verse(i)]` — the brackets turn the verse string into a one-element list, so `+` is
  *list + list* and appends one element. `verses.append(sing_verse(i))` does the same thing in place.
- `range(100, 97, -1)` — 100, 99, 98: start, stop (not included), step.
- `"".join(verses)` — glues the elements together with nothing between them (each verse already ends in `\n`).

**Expected output.** A list of **3 strings**, one verse each; `verses[0]` prints the 100-bottles verse.

**Common mistakes.**
- `verses = verses + sing_verse(i)` → `TypeError: can only concatenate list (not "str") to list`. Without
  the brackets Python tries to add a string to a list.
- `verses = verses.append(...)` → `verses` becomes `None` after the first step (`append` changes the list and
  returns `None`), and the second step fails with `AttributeError: 'NoneType' object has no attribute 'append'`.
- Keeping `song = ""` from the textbook and ending up with one long string again — check `type()` and `len()`.
- `sing_verse(i)` *printed* inside the loop instead of stored — nothing accumulates.

2.  Complete the first bullet of the Check-in before Section 7.3.

    Write a function `sqrt_pos_unvec()` that takes in a single value as an argument, and returns the square root if the value is positive. Then, write a for loop that uses this function to construct a new vector where the positive values are square rooted.

### Solution 2 — `sqrt_pos_unvec()` and a `for` loop

**Approach.** The function handles **one** value: if it is positive return its square root, otherwise return it
unchanged. Because of the `if`, the function cannot take a whole array, so a `for` loop feeds it one value at a
time and collects the results.

In [5]:
def sqrt_pos_unvec(val):
  if val > 0:
    return np.sqrt(val)
  return val                                 # not positive: leave it alone

sqrt_pos_unvec(7), sqrt_pos_unvec(-2), sqrt_pos_unvec(0)

(np.float64(2.6457513110645907), -2, 0)

In [6]:
a_vec = np.array([-2, 1, -3, -9, 7])

result = []
for val in a_vec:
  result = result + [sqrt_pos_unvec(val)]

result = np.array(result)                    # back to a numpy array
result

array([-2.        ,  1.        , -3.        , -9.        ,  2.64575131])

In [7]:
sqrt_pos_unvec(a_vec)                        # why the loop is needed: the if cannot judge a whole array

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**What the code does.**
- `if val > 0:` compares **one number** to 0, so it gives one `True`/`False` — exactly what `if` needs.
- The second `return val` runs only when the `if` did not return — the non-positive values pass through.
- The loop is the textbook's accumulate pattern: empty list → add one result per value → convert to an array.
- Handing the whole array to the function raises `ValueError: The truth value of an array with more than one
  element is ambiguous` — the same error as Section 7.2.2, and the reason this function is *unvectorized*.

**Expected output.** `(np.float64(2.6457513110645907), -2, 0)` for the single-value tests, and
`array([-2., 1., -3., -9., 2.64575131])` from the loop.

**Common mistakes.**
- **No `else` path** — a function whose only `return` is inside the `if` returns `None` for negatives, so the
  result is `[-2 → None, ...]`. ("Returns the square root if positive" still needs a decision for the rest.)
- `result.append(...)` with `result = result.append(...)` — the `None` problem from Question 1.
- `np.sqrt(val)` on a negative value — `nan` plus a `RuntimeWarning`, which is what happens if the `if` is
  written as `if val > 0: val = np.sqrt(val)` and the function then returns `np.sqrt(val)` anyway.
- Writing the loop over `range(len(a_vec))` and indexing — works, but `for val in a_vec` is the Python idiom.

3.  Complete the second bullet of the Check-in before Section 7.3.

    Write a function `sqrt_pos_vec()` that takes in a vector of values, and returns a vector with the positive values square rooted. Do not use a for loop inside your function.

### Solution 3 — `sqrt_pos_vec()` without a loop

**Approach.** Replace the `if` with a **boolean mask** (Section 7.2.2): `vec > 0` is an array of `True`/`False`,
and it can select exactly the positive entries to overwrite. Two details make it safe: work on a **copy** so the
caller's array is not changed, and make it a **float** array so square roots are not truncated to integers.

In [8]:
def sqrt_pos_vec(vec):
  out = np.array(vec, dtype = float)         # a float COPY: sqrt(7) must not become 2
  is_pos = out > 0                           # one True/False per element
  out[is_pos] = np.sqrt(out[is_pos])         # replace only the positive entries
  return out

a_vec = np.array([-2, 1, -3, -9, 7])
sqrt_pos_vec(a_vec)

array([-2.        ,  1.        , -3.        , -9.        ,  2.64575131])

In [9]:
print(a_vec)                                 # the input is untouched ...
print(sqrt_pos_vec([-4, 16, 0, 2.25]))      # ... and a plain list works too

[-2  1 -3 -9  7]
[-4.   4.   0.   1.5]


Why the two details matter — the textbook's version, applied to an integer array **in place**:

In [10]:
a_int = np.array([-2, 1, -3, -9, 7])
is_pos = a_int > 0
a_int[is_pos] = np.sqrt(a_int[is_pos])
a_int, a_int.dtype                          # sqrt(7) = 2.64... was stored as 2, and a_int itself changed

(array([-2,  1, -3, -9,  2]), dtype('int64'))

**What the code does.**
- `np.array(vec, dtype=float)` makes a new float array from whatever came in (list or array). Without `dtype=float`,
  an integer input stays integer and numpy **truncates** 2.64 → 2 when storing it. Without the copy, the function
  silently modifies the caller's array (the `a_int` demonstration).
- `out > 0` is vectorized: it compares every element at once and returns a boolean array — no `if` needed.
- `out[is_pos]` on the left selects where to write; on the right it selects what to take the square root of, so
  `np.sqrt` never sees a negative number (no `nan`, no warning).

**Expected output.** `array([-2., 1., -3., -9., 2.64575131])` — the same values as Question 2, in one
vectorized step. The in-place integer version gives `array([-2, 1, -3, -9, 2])` with dtype `int64`.

**Common mistakes.**
- **`if vec > 0:` inside the function** → the ambiguous-truth-value `ValueError`. That is the loop-shaped
  thinking the question asks you to drop.
- **Integer truncation** — `array([-2, 1, -3, -9, 2])` looks plausible enough that students do not notice.
- **`np.sqrt(vec)` then masking** — computes square roots of the negatives first: `RuntimeWarning: invalid
  value encountered in sqrt`. Mask first, then square-root.
- **Modifying the input** — the caller's `a_vec` changes; a function should return a new object (Week 6 scope).
- `np.where(vec > 0, np.sqrt(vec), vec)` is a one-line alternative but still evaluates `np.sqrt` on the whole
  array (warning); `np.where(vec > 0, np.sqrt(np.clip(vec, 0, None)), vec)` avoids it.

4.  Complete the Check-in before Section 7.4.
    - a. Write a `sing_verse_3()` function that also lets us change the container (e.g. bottle, can, …) at each step of the loop.
    - b. Use `map()` to sing a few verses.
    - c. What happens if you supply three different drinks, but only two different types of containers?

### Solution 4 — `sing_verse_3()`, `map()` over three lists, and unequal lengths

**Approach.** Add a third parameter, `container`, and use it wherever the verse said "bottles". `map()` accepts
as many iterables as the function has parameters and walks them **in step**: the first number with the first
drink and the first container, and so on.

In [11]:
def sing_verse_3(num, drink, container):
  song = str(num) + " " + container + " of " + drink + " on the wall \n"
  song = song + str(num) + " " + container + " of " + drink + "\n"
  song = song + " take one down, pass it around, \n"
  song = song + str(num-1) + " " + container + " of " + drink + " on the wall \n"
  return song

print(sing_verse_3(99, "beer", "bottles"))          # (a) one verse, to test the function

99 bottles of beer on the wall 
99 bottles of beer
 take one down, pass it around, 
98 bottles of beer on the wall 



In [12]:
nums = range(100, 97, -1)
drinks = ["beer", "milk", "lemonade"]
containers = ["bottles", "cartons", "cans"]

song = map(sing_verse_3, nums, drinks, containers)   # (b) three iterables -> three arguments, in step
print("".join(list(song)))

100 bottles of beer on the wall 
100 bottles of beer
 take one down, pass it around, 
99 bottles of beer on the wall 
99 cartons of milk on the wall 
99 cartons of milk
 take one down, pass it around, 
98 cartons of milk on the wall 
98 cans of lemonade on the wall 
98 cans of lemonade
 take one down, pass it around, 
97 cans of lemonade on the wall 



In [13]:
containers_2 = ["bottles", "cans"]                   # (c) three drinks, two containers

song = list(map(sing_verse_3, nums, drinks, containers_2))
print(len(song), "verses")
print("".join(song))

2 verses
100 bottles of beer on the wall 
100 bottles of beer
 take one down, pass it around, 
99 bottles of beer on the wall 
99 cans of milk on the wall 
99 cans of milk
 take one down, pass it around, 
98 cans of milk on the wall 



No error — `map()` quietly **stops at the end of the shortest iterable**: two containers, two verses; the
third drink ("lemonade") and the third number (98) are never used. If you want that to be an error instead,
Python 3.14 added `strict=True` to `map()` (in Colab, which runs an older Python, use
`zip(nums, drinks, containers_2, strict=True)` to get the same check):

In [14]:
list(map(sing_verse_3, nums, drinks, containers_2, strict = True))     # Python 3.14+

ValueError: map() argument 3 is shorter than arguments 1-2

**What the code does.**
- `sing_verse_3(num, drink, container)` builds the verse one line at a time, `container` replacing the hard-coded
  "bottles". The textbook's spacing (`" on the wall \n"`) is kept so the output matches the book.
- `map(sing_verse_3, nums, drinks, containers)` — the function, then **one iterable per parameter, in the same
  order as the parameters**. Step 1 calls `sing_verse_3(100, "beer", "bottles")`, step 2
  `sing_verse_3(99, "milk", "cartons")`, step 3 `sing_verse_3(98, "lemonade", "cans")`.
- `list(...)` realizes the lazy map object; `"".join(...)` glues the verses; `print` renders the `\n`s.

**Expected output.** (a) The 99-bottles verse. (b) Three verses: 100 bottles of beer, 99 cartons of milk,
98 cans of lemonade. (c) **2 verses** (beer in bottles, milk in cans) — silently, no error. With `strict=True`:
`ValueError: map() argument 3 is shorter than arguments 1-2`.

**Common mistakes.**
- **Iterables in the wrong order** — `map(sing_verse_3, drinks, nums, containers)` → `"beer" - 1` →
  `TypeError: unsupported operand type(s) for -: 'str' and 'int'`. Match the order of the parameters.
- **Passing the lists as one argument** — `map(sing_verse_3, [nums, drinks, containers])` → `TypeError:
  sing_verse_3() missing 2 required positional arguments`.
- Expecting (c) to error or to recycle the containers (R-style recycling does not happen in Python).
- Forgetting `list()` and printing the map object itself: `<map object at 0x...>`.

5.  Complete the Check-in before Section 7.5.

    Use a lambda function with `sing_verse_3()` to sing a few verses about milk in glasses.

### Solution 5 — a lambda to hold two arguments fixed

**Approach.** Only the number should change; drink and container stay "milk" and "glasses". A lambda wraps
`sing_verse_3` into a one-argument function for `map()`, so no throw-away `sing_verse_milk_glasses()` is needed.

In [15]:
song = map(lambda i: sing_verse_3(i, "milk", "glasses"), range(100, 97, -1))
print("".join(list(song)))

100 glasses of milk on the wall 
100 glasses of milk
 take one down, pass it around, 
99 glasses of milk on the wall 
99 glasses of milk on the wall 
99 glasses of milk
 take one down, pass it around, 
98 glasses of milk on the wall 
98 glasses of milk on the wall 
98 glasses of milk
 take one down, pass it around, 
97 glasses of milk on the wall 



**What the code does.**
- `lambda i: sing_verse_3(i, "milk", "glasses")` is an anonymous function with **one** parameter, `i`. Each time
  `map` calls it with a number, it calls `sing_verse_3` with that number and the two fixed strings.
- Because the lambda takes one argument, `map` needs only **one** iterable — the numbers.

**Expected output.** Three verses: 100, 99, and 98 glasses of milk on the wall.

**Common mistakes.**
- `map(sing_verse_3, nums, "milk", "glasses")` — strings *are* iterables (of characters), so this runs and
  produces verses about `"m"` in `"g"`, then stops after 4 characters. A memorable bug to show in class.
- `map(lambda i: sing_verse_3(i, "milk", "glasses")(nums))` or calling the lambda immediately — the function
  must be *passed* to `map`, not called (Topic 6.1, Debug (c)).
- Writing `lambda i: return sing_verse_3(...)` → `SyntaxError`; a lambda's body is an expression, no `return`.
- Listing the fixed arguments in the wrong order: `sing_verse_3(i, "glasses", "milk")` sings about "milk of
  glasses".

6. Load the `penguins` dataset from the `palmerpenguins` library, as well as any other libraries you need. Then write a function that takes in information about a penguin, and returns one of the following definitions:

*   "Big Mouth Billy": Male penguins with bill length times bill depth greater than 800.
*   "Dainty Daisy": Female penguins with flipper length less than 5% of body mass.
*   "Average Adelie:" Any Adelie penguins that do not fall into either category.
*   "Other": Any penguins that do not fall into any of the categories.



### Solution 6 — a function that labels one penguin

**Approach.** Write a function for **one penguin** — the pieces of information it needs become the parameters —
and check the categories **in order**, returning as soon as one matches. The order matters only for the last two:
"Average Adelie" is defined as an Adelie that is *not* a Billy or a Daisy, so those are tested first.

In [16]:
from palmerpenguins import load_penguins

penguins = load_penguins()
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007


In [17]:
def penguin_category(species, sex, bill_length, bill_depth, flipper_length, body_mass):
  """
  Label one penguin.

  Parameters
  ----------
  species, sex : str
    From the penguins data ("Adelie", ...; "male"/"female").
  bill_length, bill_depth, flipper_length : float
    Measurements in mm.
  body_mass : float
    Body mass in grams.

  Returns
  -------
  str
    "Big Mouth Billy", "Dainty Daisy", "Average Adelie", or "Other".
  """
  if sex == "male" and bill_length * bill_depth > 800:
    return "Big Mouth Billy"
  if sex == "female" and flipper_length < 0.05 * body_mass:
    return "Dainty Daisy"
  if species == "Adelie":
    return "Average Adelie"
  return "Other"

In [18]:
# Unit tests: one hand-made penguin per category
print(penguin_category("Gentoo", "male", 50.0, 17.0, 230, 6000))     # 50*17 = 850 > 800 -> Billy
print(penguin_category("Adelie", "female", 36.0, 17.0, 180, 3800))    # 180 < 0.05*3800 = 190 -> Daisy
print(penguin_category("Adelie", "male", 39.0, 18.0, 190, 3700))      # 39*18 = 702 -> not Billy; Adelie -> Average
print(penguin_category("Chinstrap", "female", 46.0, 17.0, 195, 3500)) # 195 > 175 -> not Daisy; not Adelie -> Other

Big Mouth Billy
Dainty Daisy
Average Adelie
Other


In [19]:
# ... and the first real penguin in the data
first = penguins.iloc[0]
first["species"], first["sex"], penguin_category(first["species"], first["sex"], first["bill_length_mm"],
                                                 first["bill_depth_mm"], first["flipper_length_mm"], first["body_mass_g"])

('Adelie', 'male', 'Average Adelie')

**What the code does.**
- Each parameter is one piece of "information about a penguin"; naming them after the columns keeps Question 7
  easy to write.
- `sex == "male" and bill_length * bill_depth > 800` — both conditions in one `if`; the first `return` that fires
  ends the function, so later tests are skipped.
- The two sexes make Billy and Daisy mutually exclusive, so their order does not matter; "Average Adelie" must
  come **after** them, and the final `return "Other"` catches everything else.
- A penguin with a **missing sex** (`NaN`, 11 of them) fails both `==` tests and lands in Adelie/Other —
  reasonable, and worth saying out loud.

**Expected output.** `Big Mouth Billy`, `Dainty Daisy`, `Average Adelie`, `Other` for the four test penguins; the
first real penguin (an Adelie male, 39.1 × 18.7 = 731) is an `Average Adelie`.

**Common mistakes.**
- **Writing the function for the whole column** — `if penguins["sex"] == "male"` → the ambiguous-truth-value
  error from Question 3. This function is deliberately *un*vectorized; that is why Question 7 needs `.apply`.
- **Testing `species == "Adelie"` first** — then every Adelie is "Average", including the 19 Billys and 6 Daisys.
- **Capitalization** — the data has `"male"`/`"female"` and `"Adelie"`; `"Male"` matches nothing.
- **Body-mass units** — 5% of body mass in *grams* (e.g. 190) is compared with flipper length in *mm*; that is
  the definition as given, even though the units differ. Students who "fix" the units get different counts.
- Returning the labels with inconsistent spelling/spaces, which splits the counts in Question 8.

7. Use an iterable function to create a new variable in the data frame called `category_name` that adds these labels.

### Solution 7 — `.apply()` across rows

**Approach.** Section 7.5: `.apply(..., axis=1)` hands the function **one row at a time** as a Series. Since
`penguin_category` wants six separate arguments, a lambda unpacks the row's columns into them.

In [20]:
penguins["category_name"] = penguins.apply(
  lambda row: penguin_category(row["species"], row["sex"], row["bill_length_mm"], row["bill_depth_mm"],
                               row["flipper_length_mm"], row["body_mass_g"]),
  axis = 1)

penguins[["species", "sex", "bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g", "category_name"]].head(8)

,species,sex,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,category_name
0,Adelie,male,39.1,18.7,181.0,3750.0,Average Adelie
1,Adelie,female,39.5,17.4,186.0,3800.0,Dainty Daisy
2,Adelie,female,40.3,18.0,195.0,3250.0,Average Adelie
3,Adelie,NaN,NaN,NaN,NaN,NaN,Average Adelie
4,Adelie,female,36.7,19.3,193.0,3450.0,Average Adelie
5,Adelie,male,39.3,20.6,190.0,3650.0,Big Mouth Billy
6,Adelie,female,38.9,17.8,181.0,3625.0,Dainty Daisy
7,Adelie,male,39.2,19.6,195.0,4675.0,Average Adelie


**What the code does.**
- `axis=1` — apply across **rows** (the default, `axis=0`, would hand the function a whole column).
- `lambda row: penguin_category(row["species"], ...)` — `row` is one row as a pandas Series; `row["species"]`
  picks a value out of it. The lambda does the same job as in Question 5: it adapts the function's signature to
  what `.apply` supplies.
- The result has one label per row, in order, so it can be assigned straight into a new column.

**Expected output.** A `category_name` column of strings. In the first eight rows: row 1 is a `Dainty Daisy`
(female, flipper 186 < 0.05 × 3800 = 190), row 5 a `Big Mouth Billy` (male, 39.3 × 20.6 = 809.6 > 800), row 6
another `Dainty Daisy` (181 < 181.25), and the rest — including row 3, whose measurements are all missing — are
`Average Adelie`.

**Common mistakes.**
- **`penguins.apply(penguin_category, axis=1)`** → `TypeError: penguin_category() missing 5 required positional
  arguments` — the textbook's exact error; `.apply` passes the row as *one* argument.
- **Forgetting `axis=1`** → the lambda receives a column, `row["species"]` raises `KeyError: 'species'`.
- **Looping over the data frame** with `for i in range(len(penguins))` and `.loc[i, ...]` — works, but slow and
  verbose; the question asks for an *iterable function*.
- **`penguins.category_name = ...`** on a column that does not exist yet creates an attribute, not a column
  (pandas warns). Use `penguins["category_name"] = ...`.

8. Summarize the `category_name` variable to find the counts for each type.

### Solution 8 — counts per category

**Approach.** Counting the values of one column is `value_counts()`. A cross-tab by species is a useful check
that the definitions behaved as intended.

In [21]:
penguins["category_name"].value_counts()

category_name
Average Adelie     127
Other               84
Big Mouth Billy     71
Dainty Daisy        62
Name: count, dtype: int64

In [22]:
pd.crosstab(penguins["species"], penguins["category_name"])

category_name,Average Adelie,Big Mouth Billy,Dainty Daisy,Other
species,,,,
Adelie,127,19,6,0
Chinstrap,0,34,2,32
Gentoo,0,18,54,52


**What the code does.** `value_counts()` tabulates a column, largest group first. `pd.crosstab` counts
species × category — it shows that every "Average Adelie" is an Adelie (by construction) and that Gentoos
dominate the Daisys (long flippers but heavy bodies).

**Expected output.** **Average Adelie 127, Other 84, Big Mouth Billy 71, Dainty Daisy 62** (344 total). By
species: Adelie 127 / 19 / 6 / 0; Chinstrap 0 / 34 / 2 / 32; Gentoo 0 / 18 / 54 / 52 (Average · Billy · Daisy ·
Other).

**Common mistakes.**
- `penguins.groupby("category_name").count()` — counts every column (and under-counts where values are
  missing); `.size()` or `value_counts()` is what is meant.
- Counts that do not sum to 344 → the `.apply` was run on a filtered or `dropna()`'d copy.
- Different counts from the key usually trace back to Question 6: test order (Adelie first), units, or a typo in
  a label — `value_counts()` will show the stray label as its own row.

---
## Part 2 — Practice Activity: Iteration — INSTRUCTOR SOLUTION
*Textbook: [Section 7.5, Iterating on datasets](https://ds-ml-with-python.github.io/Course-Textbook/06-iteration.html#iterating-on-datasets)
— a row-by-row function and `.apply(axis=1)`*

**How to use this notebook.** This activity is the penguin part of PA 6.2 (Questions 6–8) on its own, with the
counting code supplied. The answers below are self-contained — they reload the data and redefine the function —
so this part runs on its own even if the PA 6.2 cells above were skipped. Same five beats: **Approach → code →
What the code does → Expected output → Common mistakes**.

0. Load the `penguins` dataset from the `palmerpenguins` library, as well as any other libraries you need.



### Solution 0 — load the data and the libraries

**Approach.** `pandas` for the data frame, `numpy` for the (optional) vectorized check, and `load_penguins` for
the data. In Colab, `palmerpenguins` is not pre-installed: run `!pip install palmerpenguins` once first.

In [23]:
# !pip install palmerpenguins          # once, in Colab
import numpy as np
import pandas as pd
from palmerpenguins import load_penguins

penguins = load_penguins()
print(penguins.shape)
penguins.head()

(344, 8)


,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007


**Expected output.** `(344, 8)` — 344 penguins; the columns used below are `species`, `sex`, `bill_length_mm`,
`bill_depth_mm`, `flipper_length_mm`, `body_mass_g`. Note the `NaN`s in row 3: two penguins have no measurements
and 11 have no recorded sex.

**Common mistakes.** `import palmerpenguins` then `load_penguins()` → `NameError`; it is
`from palmerpenguins import load_penguins` (or `palmerpenguins.load_penguins()`). Forgetting the `pip install`
in Colab → `ModuleNotFoundError: No module named 'palmerpenguins'`.

1. Write a function that takes in information about a penguin, and returns one of the following definitions:

*   "Big Mouth Billy": Male penguins with bill length times bill depth greater than 800.
*   "Dainty Daisy": Female penguins with flipper length less than 5% of body mass.
*   "Average Adelie:" Any Adelie penguins that do not fall into either category.
*   "Other": Any penguins that do not fall into any of the categories.



### Solution 1 — a function that labels one penguin

**Approach.** The function describes **one** penguin, so each piece of information is a parameter. Test the
categories in order and `return` at the first match: Billy and Daisy first (they are defined by sex and a
measurement), then "Average Adelie" (an Adelie that was *not* caught above), then "Other" for everyone left.

In [24]:
def penguin_category(species, sex, bill_length, bill_depth, flipper_length, body_mass):
  """
  Label one penguin as "Big Mouth Billy", "Dainty Daisy", "Average Adelie", or "Other".

  Parameters
  ----------
  species, sex : str
    "Adelie" / "Chinstrap" / "Gentoo" and "male" / "female", as in the penguins data.
  bill_length, bill_depth, flipper_length : float
    Measurements in mm.
  body_mass : float
    Body mass in grams.

  Returns
  -------
  str
    The category name.
  """
  if sex == "male" and bill_length * bill_depth > 800:
    return "Big Mouth Billy"
  if sex == "female" and flipper_length < 0.05 * body_mass:
    return "Dainty Daisy"
  if species == "Adelie":
    return "Average Adelie"
  return "Other"

In [25]:
# Unit tests — one hand-made penguin per category, with the arithmetic in the comment
print(penguin_category("Gentoo", "male", 50.0, 17.0, 230, 6000))      # 50 * 17 = 850 > 800          -> Billy
print(penguin_category("Adelie", "female", 36.0, 17.0, 180, 3800))     # 180 < 0.05 * 3800 = 190      -> Daisy
print(penguin_category("Adelie", "male", 39.0, 18.0, 190, 3700))       # 39 * 18 = 702; Adelie        -> Average Adelie
print(penguin_category("Chinstrap", "female", 46.0, 17.0, 195, 3500))  # 195 > 175; not Adelie        -> Other

Big Mouth Billy
Dainty Daisy
Average Adelie
Other


**What the code does.**
- The `if` lines read like the definitions: `sex == "male" and bill_length * bill_depth > 800` is "male **and**
  bill area over 800". `and` here joins two single `True`/`False` values — fine for one penguin.
- The first `return` that fires ends the function, so an Adelie Billy is a Billy, not an "Average Adelie".
- The last line, `return "Other"`, needs no `if`: anything that reached it matched nothing above.
- Because this function has `if`s inside, it is **not vectorized** — it cannot take whole columns. That is why
  the next question needs an iterable function.

**Expected output.** `Big Mouth Billy`, `Dainty Daisy`, `Average Adelie`, `Other`.

**Common mistakes.**
- **Checking `species == "Adelie"` first** → every Adelie becomes "Average", swallowing 19 Billys and 6 Daisys.
- **`"Male"` / `"Female"` / `"adelie"`** — the data is lower-case `"male"`/`"female"` and capitalized species.
- **Writing it for the whole column** (`if penguins["sex"] == "male":`) → `ValueError: The truth value of a Series
  is ambiguous`.
- **A missing `return "Other"`** → non-matching penguins get `None`, and `value_counts` silently drops them.
- Comparing flipper length (mm) with 5 % of body mass (g) looks odd, but it is the definition as written; keep it.

2. Use an iterable function to create a new variable called `category_name` that adds these labels.

### Solution 2 — `.apply()` across rows

**Approach.** `.apply(..., axis=1)` hands the function one row at a time. The row arrives as a single Series, and
`penguin_category` wants six arguments, so a lambda pulls the six columns out of the row.

In [26]:
penguins["category_name"] = penguins.apply(
  lambda row: penguin_category(row["species"], row["sex"], row["bill_length_mm"], row["bill_depth_mm"],
                               row["flipper_length_mm"], row["body_mass_g"]),
  axis = 1)

penguins[["species", "sex", "bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g", "category_name"]].head(8)

,species,sex,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,category_name
0,Adelie,male,39.1,18.7,181.0,3750.0,Average Adelie
1,Adelie,female,39.5,17.4,186.0,3800.0,Dainty Daisy
2,Adelie,female,40.3,18.0,195.0,3250.0,Average Adelie
3,Adelie,NaN,NaN,NaN,NaN,NaN,Average Adelie
4,Adelie,female,36.7,19.3,193.0,3450.0,Average Adelie
5,Adelie,male,39.3,20.6,190.0,3650.0,Big Mouth Billy
6,Adelie,female,38.9,17.8,181.0,3625.0,Dainty Daisy
7,Adelie,male,39.2,19.6,195.0,4675.0,Average Adelie


**A vectorized cross-check (optional).** The same labels without `.apply`, using boolean masks and `np.select`,
which picks the first condition that is `True` for each row — the vectorized cousin of the `if` chain:

In [27]:
is_billy = (penguins["sex"] == "male") & (penguins["bill_length_mm"] * penguins["bill_depth_mm"] > 800)
is_daisy = (penguins["sex"] == "female") & (penguins["flipper_length_mm"] < 0.05 * penguins["body_mass_g"])
is_adelie = penguins["species"] == "Adelie"

vectorized = np.select([is_billy, is_daisy, is_adelie],
                       ["Big Mouth Billy", "Dainty Daisy", "Average Adelie"], default = "Other")
(vectorized == penguins["category_name"]).all()           # True: both routes agree for every penguin

np.True_

**What the code does.**
- `axis=1` → iterate over **rows**. (The default `axis=0` would hand the lambda a whole *column*, and
  `row["species"]` would fail with `KeyError`.)
- `lambda row: penguin_category(row["species"], ...)` — the adapter between what `.apply` supplies (one row)
  and what the function expects (six values). It is the textbook's Section 7.5 pattern exactly.
- The result is a Series with one label per row, aligned by index, so it drops straight into a new column.
- `np.select(conditions, choices, default)` evaluates all the masks at once; `&` (not `and`) combines two
  boolean Series element-wise. `(vectorized == penguins["category_name"]).all()` confirms the two routes agree.

**Expected output.** In the first eight rows: rows 1 and 6 are `Dainty Daisy`, row 5 is `Big Mouth Billy`, the
rest are `Average Adelie` (including row 3, whose measurements are all `NaN` — every comparison with `NaN` is
`False`, so it falls through to the species test). The cross-check prints `True`.

**Common mistakes.**
- **`penguins.apply(penguin_category, axis=1)`** → `TypeError: penguin_category() missing 5 required positional
  arguments: ...` — `.apply` passes the row as one argument.
- **Leaving out `axis=1`** → `KeyError: 'species'`.
- **`map(penguin_category, penguins)`** — iterating a data frame yields its *column names*, not rows.
- **`for i in range(len(penguins)): penguins.loc[i, "category_name"] = ...`** — works but slow and not what
  "iterable function" asks for.
- **Using `and`/`or` in the vectorized version** → the ambiguous-truth-value error; element-wise needs `&`/`|`.

3. Run the following code to find the counts for each type.

In [28]:
penguins.value_counts("category_name")

category_name
Average Adelie     127
Other               84
Big Mouth Billy     71
Dainty Daisy        62
Name: count, dtype: int64

### Solution 3 — the counts

**What the code does.** `DataFrame.value_counts("category_name")` counts how many rows take each value of that
column, largest first — the same numbers as `penguins["category_name"].value_counts()`.

**Expected output.** **Average Adelie 127 · Other 84 · Big Mouth Billy 71 · Dainty Daisy 62** (sums to 344).

**Common mistakes.**
- Counts that do not add to 344 → the labels were computed on a filtered or `dropna()`'d copy of the data.
- An extra row with a misspelled label (`"Dainty Daisy "`, `"Big mouth Billy"`) → a typo in Question 1's strings.
- `NameError: name 'penguins' is not defined` → the given cell was run before Question 0 (or after a kernel restart).
- Different numbers from the key almost always trace back to **test order** in Question 1 (Adelie checked first
  gives Average Adelie 152, Billy 52, Daisy 56, Other 84).