#!/usr/bin/env python3
"""Build docs/index.html for the course website from site_config.json.

Usage:  python3 tools/build_site.py        (run from the repo root, then commit)

Publishing rules, per item in site_config.json:
  "publish": false          -> the whole item shows only its "placeholder" text
  "publish_solution": false -> student links show, solution shows "solution_placeholder"
Files always stay in the repository; this only controls what the website links to.
NOTE: the repo itself is public, so hiding here hides from the *page*, not from
someone browsing the repository directly.
"""
import json, html, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
cfg = json.load(open(ROOT / "site_config.json"))
REPO, BR = cfg["repo"], cfg["branch"]

def links(path):
    colab = f"https://colab.research.google.com/github/{REPO}/blob/{BR}/{path}"
    view  = f"https://github.com/{REPO}/blob/{BR}/{path}"
    return (f'<a class="btn colab" href="{colab}">Open in Colab</a>'
            f'<a class="btn" href="{view}">View notebook</a>')

rows = []
for wk in cfg["weeks"]:
    rows.append(f'<h2>{html.escape(wk["label"])}</h2>')
    for it in wk["items"]:
        title = html.escape(it["title"])
        if not it.get("publish", True):
            ph = html.escape(it.get("placeholder", "Coming soon."))
            rows.append(f'<div class="card placeholder"><h3>{title}</h3>'
                        f'<p class="soon">&#128274; {ph}</p></div>')
            continue
        body = ""
        if it.get("student"):
            body += f'<div class="row"><span class="tag">Student</span>{links(it["student"])}</div>'
        if it.get("solution"):
            if it.get("publish_solution", True):
                body += f'<div class="row"><span class="tag sol">Solution</span>{links(it["solution"])}</div>'
            else:
                ph = html.escape(it.get("solution_placeholder", "Solution not posted yet."))
                body += f'<div class="row"><span class="tag sol">Solution</span><em class="soon">{ph}</em></div>'
        rows.append(f'<div class="card"><h3>{title}</h3>{body}</div>')

page = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(cfg["title"])}</title>
<style>
 body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin: 0;
        background:#f6f7f9; color:#1c2733; }}
 main {{ max-width: 860px; margin: 0 auto; padding: 2rem 1rem 4rem; }}
 h1 {{ border-bottom: 3px solid #154734; padding-bottom:.4rem; }}
 h2 {{ color:#154734; margin-top:2.2rem; }}
 .card {{ background:#fff; border:1px solid #e2e6ea; border-radius:10px;
         padding: .9rem 1.1rem; margin:.7rem 0; }}
 .card h3 {{ margin:.1rem 0 .6rem; font-size:1.05rem; }}
 .row {{ margin:.35rem 0; display:flex; align-items:center; gap:.55rem; flex-wrap:wrap; }}
 .tag {{ font-size:.72rem; font-weight:700; text-transform:uppercase; letter-spacing:.04em;
        background:#e8f0ec; color:#154734; border-radius:4px; padding:.15rem .45rem; }}
 .tag.sol {{ background:#fdf3d7; color:#7a5b00; }}
 .btn {{ font-size:.85rem; text-decoration:none; color:#154734; border:1px solid #b9c8c0;
        border-radius:6px; padding:.25rem .6rem; background:#fff; }}
 .btn.colab {{ background:#154734; color:#fff; border-color:#154734; }}
 .btn:hover {{ filter:brightness(1.12); }}
 .placeholder {{ background:#eef1f4; border-style:dashed; }}
 .soon {{ color:#5a6a79; }}
 footer {{ color:#8a97a3; font-size:.8rem; margin-top:3rem; }}
</style></head><body><main>
<h1>{html.escape(cfg["title"])}</h1>
<p>Course notebooks. <em>Student</em> versions have blanks to fill in; <em>Solution</em>
versions are completed and rendered with outputs.</p>
{''.join(rows)}
<footer>Generated by <code>tools/build_site.py</code> from <code>site_config.json</code>.</footer>
</main></body></html>
"""
(ROOT / "docs").mkdir(exist_ok=True)
(ROOT / "docs" / "index.html").write_text(page)
(ROOT / "docs" / ".nojekyll").write_text("")
print("wrote docs/index.html")
